apiVersion: v1
kind: Pod
metadata:
  name: pod-pv-pvc-practice
spec:
  containers:
    - name: pvc-pv-pod
      image: nginx:1.25.3
      ports:
      - containerPort: 80

      resources:
        limits:
          memory: "64Mi"
          cpu: "250m" 
        requests:
          memory: "64Mi"
          cpu: "250m" 

      volumeMounts:
        - name: app-pvc-pv-storage
          mountPath: /usr/share/nginx/html
  
  volumes:
    - name: app-pvc-pv-storage
      persistentVolumeClaim:
        claimName: pvc-practice 


